USE [master]
GO

/****** Object:  Database [Fama_bayer]    Script Date: 12/6/2025 22:11:00 ******/
CREATE DATABASE [Fama_bayer]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'Fama_bayer', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\Fama_bayer.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'Fama_bayer_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL14.SQLEXPRESS\MSSQL\DATA\Fama_bayer_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
GO

IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [Fama_bayer].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO

ALTER DATABASE [Fama_bayer] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [Fama_bayer] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [Fama_bayer] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [Fama_bayer] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [Fama_bayer] SET ARITHABORT OFF 
GO

ALTER DATABASE [Fama_bayer] SET AUTO_CLOSE OFF 
GO

ALTER DATABASE [Fama_bayer] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [Fama_bayer] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [Fama_bayer] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [Fama_bayer] SET CURSOR_DEFAULT  GLOBAL 
GO

ALTER DATABASE [Fama_bayer] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [Fama_bayer] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [Fama_bayer] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [Fama_bayer] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [Fama_bayer] SET  DISABLE_BROKER 
GO

ALTER DATABASE [Fama_bayer] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [Fama_bayer] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO

ALTER DATABASE [Fama_bayer] SET TRUSTWORTHY OFF 
GO

ALTER DATABASE [Fama_bayer] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO

ALTER DATABASE [Fama_bayer] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [Fama_bayer] SET READ_COMMITTED_SNAPSHOT OFF 
GO

ALTER DATABASE [Fama_bayer] SET HONOR_BROKER_PRIORITY OFF 
GO

ALTER DATABASE [Fama_bayer] SET RECOVERY SIMPLE 
GO

ALTER DATABASE [Fama_bayer] SET  MULTI_USER 
GO

ALTER DATABASE [Fama_bayer] SET PAGE_VERIFY CHECKSUM  
GO

ALTER DATABASE [Fama_bayer] SET DB_CHAINING OFF 
GO

ALTER DATABASE [Fama_bayer] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO

ALTER DATABASE [Fama_bayer] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO

ALTER DATABASE [Fama_bayer] SET DELAYED_DURABILITY = DISABLED 
GO

ALTER DATABASE [Fama_bayer] SET QUERY_STORE = OFF
GO

ALTER DATABASE [Fama_bayer] SET  READ_WRITE 
GO

